/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FacturaComercial;

/**
 *
 * @author HP
 */
public class FacFrame extends javax.swing.JFrame {

    /**
     * Creates new form FacFrame
     */
    public FacFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        txtCant1 = new javax.swing.JTextField();
        txtCant2 = new javax.swing.JTextField();
        Product1 = new javax.swing.JTextField();
        Product2 = new javax.swing.JTextField();
        txtVal1 = new javax.swing.JTextField();
        txtVal2 = new javax.swing.JTextField();
        txtImpor1 = new javax.swing.JTextField();
        txtImpor2 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        txtIVA = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        txtTPagar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtDesc = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(51, 51, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Factura del Cliente");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 485, 40));

        jTextField2.setBackground(new java.awt.Color(102, 255, 255));
        jTextField2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Cantidad");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 52, -1, -1));

        jTextField3.setBackground(new java.awt.Color(102, 255, 255));
        jTextField3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Producto");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 52, -1, -1));

        jTextField4.setBackground(new java.awt.Color(102, 255, 255));
        jTextField4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setText("Valor Unitario");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 52, -1, -1));

        jTextField5.setBackground(new java.awt.Color(102, 255, 255));
        jTextField5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Total del producto");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 52, -1, -1));

        txtCant1.setBackground(new java.awt.Color(255, 255, 255));
        txtCant1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtCant1.setForeground(new java.awt.Color(0, 0, 0));
        txtCant1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 89, 77, -1));

        txtCant2.setBackground(new java.awt.Color(255, 255, 255));
        txtCant2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtCant2.setForeground(new java.awt.Color(0, 0, 0));
        txtCant2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 126, 77, -1));

        Product1.setBackground(new java.awt.Color(255, 255, 255));
        Product1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Product1.setForeground(new java.awt.Color(0, 0, 0));
        Product1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Product1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 89, 79, -1));

        Product2.setBackground(new java.awt.Color(255, 255, 255));
        Product2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Product2.setForeground(new java.awt.Color(0, 0, 0));
        Product2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Product2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 126, 79, -1));

        txtVal1.setBackground(new java.awt.Color(255, 255, 255));
        txtVal1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtVal1.setForeground(new java.awt.Color(0, 0, 0));
        txtVal1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtVal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 89, 112, -1));

        txtVal2.setBackground(new java.awt.Color(255, 255, 255));
        txtVal2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtVal2.setForeground(new java.awt.Color(0, 0, 0));
        txtVal2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtVal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 126, 112, -1));

        txtImpor1.setBackground(new java.awt.Color(255, 255, 255));
        txtImpor1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtImpor1.setForeground(new java.awt.Color(0, 0, 0));
        txtImpor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtImpor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 89, 144, -1));

        txtImpor2.setBackground(new java.awt.Color(255, 255, 255));
        txtImpor2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtImpor2.setForeground(new java.awt.Color(0, 0, 0));
        txtImpor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtImpor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 126, 144, -1));

        jTextField14.setBackground(new java.awt.Color(255, 255, 255));
        jTextField14.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(0, 0, 0));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("Subtotal");
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 169, -1, -1));

        txtSubtotal.setBackground(new java.awt.Color(255, 255, 255));
        txtSubtotal.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        txtSubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 169, 114, -1));

        jTextField16.setBackground(new java.awt.Color(255, 255, 255));
        jTextField16.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(0, 0, 0));
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("IVA 25%");
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 212, -1, -1));

        txtIVA.setBackground(new java.awt.Color(255, 255, 255));
        txtIVA.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtIVA.setForeground(new java.awt.Color(0, 0, 0));
        txtIVA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 212, 114, -1));

        jTextField18.setBackground(new java.awt.Color(255, 255, 255));
        jTextField18.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(0, 0, 0));
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("Descuento");
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Total a pagar");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 298, -1, -1));

        txtTPagar.setBackground(new java.awt.Color(255, 255, 255));
        txtTPagar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtTPagar.setForeground(new java.awt.Color(0, 0, 0));
        txtTPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtTPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 298, 114, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 90, -1));

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, -1));

        txtDesc.setBackground(new java.awt.Color(255, 255, 255));
        txtDesc.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtDesc.setForeground(new java.awt.Color(0, 0, 0));
        txtDesc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 110, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cant1 = txtCant1.getText();
        String cant2 = txtCant2.getText();
        
        String v1 = txtVal1.getText();
        String v2 = txtVal2.getText();
        
        int imp1 = Integer.parseInt(cant1) * Integer.parseInt(v1);
        int imp2 = Integer.parseInt(cant2) * Integer.parseInt(v2);
        
        txtImpor1.setText(""+imp1);
        txtImpor2.setText(""+imp2);
        
        int sub = imp1 + imp2;
        txtSubtotal.setText(""+sub);
        
        double IVA25 = sub * 0.25;
        txtIVA.setText(""+IVA25);
        
        double descuento = Double.parseDouble(txtDesc.getText());
        
        double TotalPago = (sub * descuento/100)+ IVA25;
        txtTPagar.setText(""+TotalPago);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtCant1.setText(null);
        txtCant2.setText(null);
        Product1.setText(null);
        Product2.setText(null);
        txtVal1.setText(null);
        txtVal2.setText(null);
        txtImpor1.setText(null);
        txtImpor2.setText(null);
        txtSubtotal.setText(null);
        txtIVA.setText(null);
        txtDesc.setText(null);
        txtTPagar.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Product1;
    private javax.swing.JTextField Product2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtCant1;
    private javax.swing.JTextField txtCant2;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtImpor1;
    private javax.swing.JTextField txtImpor2;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTPagar;
    private javax.swing.JTextField txtVal1;
    private javax.swing.JTextField txtVal2;
    // End of variables declaration//GEN-END:variables
}
